export const teamDatabase = [
  { teamName: "Solo", password: "solo123" },
  { teamName: "Northern CyberSentinels", password: "northern456" },
  { teamName: "Voice Pioneers", password: "voice789" },
  { teamName: "YODAQ", password: "yodaq321" },
  { teamName: "Voice Craft AI", password: "craft654" },
  { teamName: "Sweet Tongue", password: "sweet987" },
  { teamName: "LUG Translators", password: "lug123" },
  { teamName: "TRANSLINQUAL.AI", password: "trans456" },
  { teamName: "Creek_IT", password: "creek789" },
  { teamName: "Team Apex", password: "apex321" },
  { teamName: "EchoTech", password: "echo654" },
  { teamName: "Kasayie", password: "kasayie987" },
  { teamName: "Anigye AI", password: "anigye123" },
  { teamName: "Team Synchronia", password: "sync456" },
  { teamName: "Twilight", password: "twilight789" },
  { teamName: "DISAL", password: "disal321" },
  { teamName: "Pentalingual Devs", password: "penta654" },
  { teamName: "DevForChange(DFC)", password: "dfc987" },
  { teamName: "SSS", password: "sss123" },
  { teamName: "Excellence", password: "excel456" },
  { teamName: "Team WRAPE", password: "wrape789" },
  { teamName: "Wummiya", password: "wummiya321" },
  { teamName: "Kodietech", password: "kodie654" },
  { teamName: "Wiemo team", password: "wiemo987" },
  { teamName: "GONGO TECH", password: "gongo123" },
  { teamName: "Team Kasa Nimdie", password: "kasa456" },
  { teamName: "Yerekasa", password: "yerekasa789" },
  { teamName: "OrionNerd_X", password: "orion321" },
  { teamName: "YADAH", password: "yadah654" },
  { teamName: "CodeBlooded", password: "code987" },
  { teamName: "Nsem Tech", password: "nsem123" },
  { teamName: "Team EchoVoice", password: "echo456" },
  { teamName: "GeekTeam", password: "geek789" },
  { teamName: "HandWave", password: "wave321" },
  { teamName: "TEAM VOXAURA", password: "voxaura654" },
  { teamName: "VoiceGhana", password: "ghana987" },
  { teamName: "TEAM IJB", password: "ijb123" },
  { teamName: "SproutAI", password: "sprout456" },
  { teamName: "WhisperWave", password: "whisper789" },
  { teamName: "Code4Voice", password: "code432" },
  { teamName: "KASA NOMA", password: "noma654" },
  { teamName: "Htu Sharks", password: "sharks987" },
  { teamName: "ADVIS", password: "advis123" },
  { teamName: "Waakye", password: "waakye456" },
  { teamName: "Admin", password: "admin789" },
  { teamName: "TwiTalk", password: "twitalk123" },
  { teamName: "Alpha", password: "alpha456" },
  { teamName: "Semantic Sensei", password: "sensei789" },
  { teamName: "KasaYie", password: "kasayie123" },
];
